name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package

      - name: Get version
        id: version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.version.outputs.VERSION }}" \
            --title "SimpleEco v${{ steps.version.outputs.VERSION }}" \
            --notes "## SimpleEco v${{ steps.version.outputs.VERSION }}

          Automatisch erstelltes Release.

          ### Installation
          1. Download der \`SimpleEco.jar\`
          2. In den \`plugins/\` Ordner kopieren
          3. Server neustarten" \
            "./target/SimpleEco-${{ steps.version.outputs.VERSION }}.jar#SimpleEco.jar"
